import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { ImLinkedin2 } from "react-icons/im";
import { SiFiverr } from "react-icons/si";
import { SiUpwork } from "react-icons/si";
import Image from "next/image";
import devet from "../public/mdr_pic5.png";
import { useState } from "react";
import { useRouter } from "next/router";
import Services from "../components/Services";
import TabsData from "../components/TabsData";
import Footer from "../components/Footer";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const router = useRouter();
  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>MDR Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gradient-to-b from-gray-900 to-teal-900 pb-12">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-300">MDR</h1>
            <ul className="flex justify-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="text-2xl cursor-pointer dark:text-white"
                />
              </li>
              <li>
                <a
  href="/Dawood_Rafique_Resume.pdf"
  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
  download
>
  Resume
</a>
              </li> 
            </ul>
          </nav>
          <div className="relative mx-auto bg-gradient-to-t from-teal-600 to-teal-900 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96">
            <Image
              src={devet}
              width={500}
              height={500}
              alt="img"
              className=""
            />
          </div>
          <div className="text-center p-12">
            <h2 className="py-2 text-4xl text-teal-600 dark:text-teal-500 font-medium md:text-6xl font-burtons">
              M Dawood Rafique
            </h2>
            <h3 className="text-2x py-2 md:text-2xl font-mono font-bold dark:text-gray-300">
            Helping bring digital products to life  
            </h3>
            <p className="text-md leading-8 dark:text-gray-400 md:text-l max-w-xl mx-auto  text-gray-600">
              Specializing in WordPress, web programming, and content design,
              with expertise in DevOps, including application deployment on AWS
              and other cloud platforms. Let's connect and bring ideas to life!
            </p>
          </div>
          <div className="text-5xl flex justify-center items-center gap-8 lg:gap-12 py-3 text-gray-600">
            <a href="https://www.fiverr.com/muhammaddawoo" className="text-8xl">
              <SiFiverr />
            </a>
            <a
              href="https://www.upwork.com/freelancers/muhammaddawood"
              className="text-5xl mt-2"
            >
              <SiUpwork />
            </a>
            // <a href="https://www.linkedin.com/in/mdr394" className="text-4xl">
            //   <ImLinkedin2 />
            // </a>
          </div>
        </section>

        <Services />

        <section className="mb-7">
          <h3 className="text-4xl py-1 mt-10 font-bold dark:text-teal-500">
            Portfolio
          </h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
            Here are some of the projects I've worked on for{" "}
            <spam className="text-teal-500 dark:text-teal-500">
              agencies, organizations, and startups,
            </spam>{" "}
            delivering high-quality solutions tailored to their needs. This
            version improves flow, clarity, and professionalism while keeping it
            engaging. Let me know if you'd like further tweaks! 🚀
          </p>
        </section>

        <TabsData />
      </main>
      <Footer />
    </div>
  );
}
